### ISSUE TITLE
model/backend attribute missing

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/scidash-api#30]
I'm not sure what it is looking for exactly.  

![screen shot 2018-05-03 at 10 49 13 pm](https://user-images.githubusercontent.com/549787/39614389-52fccace-4f24-11e8-83cf-4f32a375ef52.png)

**Comment by gidili** [comment]
Hi @rgerkin I think it's looking for the model backend attribute, as in: `'backend': 'jNeuroML'`

Is that meant to be an optional attribute? It's not even getting to validation as the attribute seems to be missing from the json.

**Comment by gidili** [comment]
The model/backend parameter is now optional (merged into development branch) https://github.com/MetaCell/scidash-api/compare/ef64d02702ff...a18751ba528f
