### ISSUE TITLE
Idea for client-side warnings about server-side validation errors

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/scidash-api#31]
Let's automatically generate a warning to the client to match any server-side status codes that could be considered errors (e.g. 400).  
```
import json
x = client_instance.upload_suite_score(suite,score_matrix)
for result in x:
    if hasattr(result,'_content'):
        print(json.loads(result._content.decode('utf-8'))['errors'])
```
If something like the above is run, but put into python warning messages, then it will apparent to the user why their data did not upload.

**Comment by rgerkin** [comment]
Even deeper: maybe you could also return the complete call stack for the error.  That way if I can point you directly to the source of the error, or if it turns out to be in the API I can just fix it and submit a PR.

**Comment by gidili** [comment]
This was implemented, we can open issues for improvements as needed 👍
