### ISSUE TITLE
What is a valid URL?

### ISSUE THREAD

**Issue by rgerkin** [MetaCell/scidash-api#32]
I am getting this:  
`{'score_class': {'url': ['Enter a valid URL.']}, 'model_instance': {'model_class': {'url': ['Enter a valid URL.']}}, 'test_instance': {'test_class': {'url': ['Enter a valid URL.']}}}`
as my error JSON returned by the server on a score upload.  
My `score.url` is `http://github.com/scidash/sciunit.git` and my `score.model.url` is `http://github.com/openworm/tests`.  Do these need to be formatted differently to validate?  Or is it the `score.__class__` that needs to have a `url` attribute?

**Comment by gidili** [comment]
@rgerkin after getting latest sciunit/neuronunit from dev branch seeing this now when trying to set urls: 
<img width="831" alt="screenshot 2018-05-04 21 30 18" src="https://user-images.githubusercontent.com/68134/39651092-7cbd910e-4fe2-11e8-9f90-c2374fc6ba5b.png">

**Comment by rgerkin** [comment]
@gidili Yes, because `url` is now a property which reads `_url` (if it is set) or the read-only property `remote_url` if it is not.  So in the examples I am working with I am not setting `url` directly anymore; is the API?

**Comment by rgerkin** [comment]
Is it possible that the validator is requiring the attribute itself to be a string, rather than just what is returned by calling the attribute?  In other words, `model.url` will evaluate as a string (`isinstance(model.url,str)` evaluates to `True`), but the class attribute is a property (`isinstance(score.model.__class__.url,property)` evaluates to True).  If so, this is a problem because all that should be required is that accessing the attribute gets the correct data type; there should be no requirements about how that is implemented in SciUnit.

**Comment by rgerkin** [comment]
Disregard the above.  It was indeed the difference between the `_class` property's `url` and the instance's own `url`, but I forced the former to always give a string (empty if necessary) in scidash/sciunit@adf7793 and it solved the problem.  This allowed me to upload the data.

**Comment by gidili** [comment]
@rgerkin ah, mystery solved! Glad to hear you got it sorted and managed to upload! 🎉
